CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, username TEXT NOT NULL, hash TEXT NOT NULL, balance_cents NUMERIC NOT NULL DEFAULT 1000000.00);
CREATE TABLE purchases (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, uuid INTEGER NOT NULL, price_cents INTEGER NOT NULL, shares INTEGER NOT NULL, symbol TEXT NOT NULL, time DATETIME NOT NULL);
CREATE TABLE sells (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, uuid INTEGER NOT NULL, price_cents INTEGER NOT NULL, shares INTEGER NOT NULL, symbol TEXT NOT NULL, time DATETIME NOT NULL);